#version: '3.8'

services:
  # Service de l'application PHP
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  # Service Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Accès via http://localhost:8080
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

# Réseau Docker
networks:
  laravel:
    driver: bridge